Repository hyundai-fruitfruit/frontend, pull requests merged in 2024-03, with the labels that each got.

#24 Heendy 85 mbti page
  src/App.js
  src/assets/data/mbtiContent.jsx
  src/assets/icons/Fortune-cookie.png
  src/assets/icons/Framed-picture.png
  src/assets/icons/Grinning-face-with-smiling-eyes.png
  src/assets/icons/Parachute.png
  src/assets/icons/Shushing-face.png
  src/assets/icons/Spiral-calendar.png
  src/assets/icons/Wrapped-gift.png
  src/assets/icons/Writing-hand.png
  src/components/CouponCard/CouponCard2.jsx
  src/components/SpeechBubble/SpeechBubble.jsx
  src/pages/Mbti/Mbti.jsx
Labels: 💡 feature, 🔥 H-5, 🐻 가브리엘

#25 [HEENDY-82-friend] 쿠폰, 이벤트 api 연결, 매장 상세페이지, 리뷰 목록 api 연결, 리뷰 작성 페이지 구현 및 api 연결
  src/App.js
  src/apis/request.js
  src/assets/data/Hashtags.jsx
  src/assets/icons/floor_icon.png
  src/assets/icons/rating_icon.png
  src/assets/icons/store_number_icon.png
  src/components/CouponCard/CouponCard.jsx
  src/components/DisplayShopDetails/DisplayShopDetails.jsx
  src/components/ModalBubbleContent/MainPageModalContent.jsx
  src/components/RatingStar/InputRatingStar.jsx
  src/components/StoreReview/StoreHashTag.jsx
  src/components/StoreReview/StoreReview.jsx
  src/components/StoreReview/StoreReviewList.jsx
  src/components/StoreReview/StoreReviewPage.jsx
  src/components/StoreReview/StoreTotalReview.jsx
  src/hooks/useGetEventList.jsx
  src/hooks/useGetUserCouponList.jsx
  src/pages/CouponTab/CouponTab.jsx
  src/pages/MainPage/EventNotice.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/ReviewCreation/ReviewCreation.jsx
  src/pages/ReviewCreation/ReviewEditor.jsx
  src/pages/StoreDetail/StoreDetail.jsx
Labels: 🐶 KK, 💡 feature, 🔥 H-5

#27 [Heendy 86 fcm join] FCM 푸시 알림 요청 및 알림 클릭 시 페이지 이동 구현
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  public/index.html
  src/apis/request.js
  src/assets/icons/login_google.png
  src/assets/icons/login_kakao.png
  src/assets/models/Coffee.jsx
  src/assets/models/Coke.jsx
  src/assets/models/Deer.jsx
  src/assets/models/Flower.jsx
  src/assets/models/Flower2.jsx
  src/assets/models/Hamburger.jsx
  src/assets/models/Pizza.jsx
  src/assets/models/Popcorn.jsx
  src/assets/models/Tree1.jsx
  src/assets/models/Tree2.jsx
  src/config.js
  src/firebase-messaging-sw.js
  src/pages/Login/Login.jsx
  src/pages/Login/firebase.js
  src/pages/MyRoom/MyRoom.jsx
  src/pages/Onboarding/Onboarding.jsx
Labels: 💡 feature, 👻 팻치

#34 [HEENDY-95-mbti-friend-CSS] 친구, 쿠폰 페이지 연결
  my-pwa/public/index.html
  my-pwa/public/manifest.json
  public/index.html
  src/apis/request.js
  src/components/QRScanner/MyQrLoader.jsx
  src/components/SpeechBubble/SpeechBubble.css
  src/pages/CouponTab/CouponTab.jsx
  src/pages/FriendGame/FriendGame.jsx
  src/pages/Mbti/Mbti.jsx
  src/pages/RandomEventSpot/RandomEventSpotQR.jsx
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#37 [HEENDY-106-friend-CSS] 친구 페이지 일관성 있게 스타일 수정
  src/App.js
  src/assets/icons/icon-love-letter.png
  src/assets/icons/icon-mood.png
  src/assets/icons/icon-weather.png
  src/assets/images/event-card-detail.png
  src/assets/images/heendy-background.png
  src/components/Dice/DiceBoard.jsx
  src/components/Header/MainHeader.jsx
  src/components/Header/SubHeader.jsx
  src/components/IconMenu/FriendMenu.jsx
  src/components/ModalBubbleContent/ProgressBar.jsx
  src/pages/CaptainHeendy/CaptainHeendy.jsx
  src/pages/ChatBot/ChatBot2.jsx
  src/pages/FriendGame/Dice.jsx
  src/pages/FriendGame/FriendGame.jsx
  src/pages/FriendGame/GetExp.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/MyRoom/MyRoom.jsx
  src/pages/RandomEventSpot/RandomEventSpotQRSuccess.jsx
  tailwind.config.js
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#39 [HEENDY-109-redux-fix] redux 적용을 위해 location.href 대신 navigate 사용
  src/pages/CaptainHeendy/CaptainHeendy.jsx
  src/pages/RandomEventSpot/EventDetail.jsx
  src/pages/RandomEventSpot/RandomSpotResult.jsx
  src/pages/RandomEventSpot/RandomsSpotPush.jsx
Labels: 🐞 fix, 🔥 H-1, 🐻‍❄️ 연유

#43 [HEENDY-110-exp-levelup] 경험치, 레벨업 페이지
  src/App.js
  src/assets/images/event-card-detail.png
  src/assets/images/heendy-cap-background.png
  src/components/CouponCard/CouponCard2.jsx
  src/components/QRScanner/MyQrLoader.jsx
  src/hooks/animation/useProgress.jsx
  src/pages/CouponTab/CouponTab.jsx
  src/pages/FriendGame/FriendGame.jsx
  src/pages/FriendGame/GetExp.jsx
  src/pages/FriendGame/LevelUp.jsx
  src/pages/Location/GPSPage.jsx
  src/pages/Mbti/Mbti.jsx
  src/pages/Mbti/MbtiResult.jsx
  src/pages/RandomEventSpot/RandomEventSpotQRSuccess.jsx
  src/pages/RandomEventSpot/RandomsSpotPush.jsx
  src/store/features/LevelSlice.js
Labels: 💡 feature, 🐻‍❄️ 연유

#44 Heendy 115 fix review 리뷰 다중 이미지 업로드 및 리뷰 조회 시 해시태그, 닉네임, 프로필 조회 추가
  src/components/StoreReview/StoreReview.jsx
  src/components/StoreReview/StoreReviewList.jsx
  src/components/StoreReview/StoreTotalReview.jsx
  src/pages/ReviewCreation/ReviewEditor.jsx
  src/pages/StoreDetail/StoreDetail.jsx
Labels: 🐞 fix, 🔥 H-1, 👻 팻치

#48 [HEENDY-114-GPS-fix] GPS 페이지 조정
  PULL_REQUEST_TEMPLATE.md
  src/apis/request.js
  src/components/CouponCard/CouponCard2.jsx
  src/components/Header/SubHeader.jsx
  src/pages/CouponTab/CouponTab.jsx
  src/pages/FriendGame/LevelUp.jsx
  src/pages/Location/GPSPage.jsx
  src/pages/Location/GPSSuccess.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/Mbti/Mbti.jsx
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#49 [HEENDY-114-GPS-fix] GPS 페이지 연결
  src/assets/data/mbtiContent.jsx
  src/assets/images/event2.png
  src/components/CouponCard/CouponCard2.jsx
  src/components/ModalBubbleContent/MainPageModalContent.jsx
  src/pages/CouponTab/CouponTab.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/RandomEventSpot/EventDetail.jsx
  src/pages/TheHyundaiMap/TheHyundaiMap.jsx
Labels: 🐞 fix, 🔥 H-1, 🐻‍❄️ 연유
