Repository hyundai-fruitfruit/frontend, pull requests merged in 2024-02, with the labels that each got.

#6 로그인페이지, 메인페이지, 말풍선, 말풍선 링크, 랜덤이벤트 모달, 이벤트 결과 모달 구현
  .prettierrc.json
  src/App.js
  src/assets/images/coupon_icon.png
  src/assets/images/display_icon.png
  src/assets/images/heendy_background.png
  src/assets/images/heendy_background2.png
  src/assets/images/item_icon.png
  src/assets/images/main_heendy.png
  src/assets/images/smt_img.png
  src/assets/images/start_icon.png
  src/components/BackgroundImage/BackgroundImage.js
  src/components/ClaymorphicButton/ClaymorphicButton.css
  src/components/ClaymorphicButton/ClaymorphicButton.js
  src/components/IconMenu/IconMenu.js
  src/components/ModalComponent/ModalComponent.js
  src/components/SpeechBubble/SpeechBubble.css
  src/components/SpeechBubble/SpeechBubble.js
  src/hooks/useModal.js
  src/pages/Login/Login.js
  src/pages/MainPage/Mainpage.js
  src/pages/RandomEventSpot/RandomEventSpot.js
Labels: feat

#10 [HEENDY-39-UI제작] 이벤트 모달, 매장 상세페이지, 리뷰 페이지, 리뷰 작성페이지 구현
  .eslintrc.js
  package-lock.json
  package.json
  public/images/smt_lounge1.jpeg
  public/images/smt_lounge2.jpeg
  public/images/smt_lounge3.jpeg
  src/App.js
  src/apis/api.js
  src/apis/request.js
  src/assets/data/Hashtags.jsx
  src/assets/images/Lazji.png
  src/assets/images/Szechuan_Spicy_Eggplant.png
  src/assets/images/beef_steak_taco.png
  src/components/BackgroundImage/BackgroundImage.jsx
  src/components/BottomNavbar/BottomNavbar.jsx
  src/components/ClaymorphicButton/ClaymorphicButton.css
  src/components/ClaymorphicButton/ClaymorphicButton.jsx
  src/components/DisplayShopDetails/DisplayShopDetails.jsx
  src/components/DisplayShopTabs/DisplayShopTabs.jsx
  src/components/DropdownMenu/DropdownMenu.jsx
  src/components/Header/Header.jsx
  src/components/IconMenu/IconMenu.jsx
  src/components/ImageSlide/ImageScroll.jsx
  src/components/ImageSlide/ImageSlide.jsx
  src/components/Location/LocationDisplay.jsx
  src/components/ModalComponent/ModalComponent.jsx
  src/components/QRScanner/QRScannerComponent.jsx
  src/components/RandomEventCard/RandomEventCard.jsx
  src/components/RatingStar/InputRatingStar.jsx
  src/components/SideScrollImage/SideScrollImage.jsx
  src/components/StoreMenu/StoreMenu.jsx
  src/components/StoreMenu/StoreMenuList.jsx
  src/components/StoreReview/HashtagElement.jsx
  src/components/StoreReview/HashtagSelection.jsx
  src/components/StoreReview/StoreHashTag.jsx
  src/components/StoreReview/StoreReview.jsx
  src/components/StoreReview/StoreReviewList.jsx
  src/components/StoreReview/StoreReviewPage.jsx
  src/components/StoreReview/StoreTotalReview.jsx
  src/hooks/useCreateReview.jsx
  src/hooks/useCurrentLocation.jsx
  src/hooks/useModal.jsx
  src/hooks/useRandomSpotByEventType.jsx
  src/hooks/useStoreDetails.jsx
  src/pages/Layouts/RootLayout.jsx
  src/pages/Location/LocationPage.jsx
  src/pages/Login/Login.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/QRScannerPage/QRScannerPage.jsx
  src/pages/RandomEventSpot/RandomEventSpot.jsx
  src/pages/ReviewCreation/ReviewCreation.jsx
  src/pages/ReviewCreation/ReviewEditor.jsx
  src/pages/StoreDetail/StoreDetail.jsx
Labels: bug, feat

#11 누락된 icons directory 추가
  src/assets/icons/Icons left.png
  src/assets/icons/camera_icon.png
  src/assets/icons/floor_icon.png
  src/assets/icons/rating_icon.png
  src/assets/icons/store_number_icon.png
Labels: 🐞 fix

#12 fix : fix camera_icon path
  src/pages/ReviewCreation/ReviewEditor.jsx
Labels: 🐞 fix, 🐶 KK

#16 [HEENDY-65-kakao-login] 프록시 세팅 및 카카오 로그인 연결
  package.json
  src/App.js
  src/apis/api.js
  src/apis/request.js
  src/apis/requests/kakaoRequest.js
  src/pages/Login/KakaoCallback.js
  src/pages/Login/Login.jsx
  src/setupProxy.js
Labels: 💡 feature, 🐻‍❄️ 연유

#17 feat: 쿠폰페이지 - QR, Coupon, 이벤트페이지 구현
  src/App.js
  src/assets/icons/bottle_icon.png
  src/assets/icons/flying_money_icon.png
  src/assets/icons/heart_icon.png
  src/assets/icons/hotdog_icon.png
  src/assets/icons/kakao_login.png
  src/assets/icons/old_key_icon.png
  src/assets/icons/red_envelope_icon.png
  src/components/CouponCard/CouponCard.jsx
  src/pages/CouponTab/CouponTab.jsx
  src/pages/Login/Login.jsx
  src/pages/MainPage/EventNotice.jsx
  src/pages/MainPage/Mainpage.jsx
  src/pages/Test/TestHooksApis.jsx
  src/pages/Test/TestPage.jsx
Labels: 🐶 KK, 💡 feature, 🔥 H-5

#18 [HEENDY-‪46-QR-socket] 유저 소켓에서 메세지 구독
  package.json
  src/apis/request.js
  src/hooks/useQr.jsx
  src/hooks/useSocket.jsx
  src/index.js
  src/pages/RandomEventSpot/RandomEventSpotQR.jsx
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유

#21 [HEENDY-80-MBTI] 온보딩 페이지 추가 및 큐알 완료 시 페이지 이동
  src/App.js
  src/pages/Login/KakaoCallback.js
  src/pages/Onboarding/Onboarding.jsx
  src/pages/RandomEventSpot/RandomEventSpotQR.jsx
Labels: 💡 feature, 🔥 H-1, 🐻‍❄️ 연유
